version: "3"

services:
  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: "12345678"
      MYSQL_DATABASE: "crud_db"
    ports:
      - "3306:3306"
    networks:
      - backend-network

  backend:
    build:
      context: ./backend
    environment:
      DB_USER: "root"
      DB_PASSWORD: "12345678"
      DB_HOST: "db"
    depends_on:
      - db
    ports:
      - "3000:3000"
    command: ["sh", "-c", "sleep 10 && npm start"] # Espera 10 segundos antes de iniciar
    networks:
      - backend-network

  frontend:
    build:
      context: ./frontend
    ports:
      - "3001:3001"
    depends_on:
      - backend
    networks:
      - backend-network
    environment:
      - PORT=3001

networks:
  backend-network:
    driver: bridge
